#ifndef NIMBLE_STEPS_SERIALIZE_TYPES_H
#define NIMBLE_STEPS_SERIALIZE_TYPES_H

typedef enum NimbleSerializeParticipantConnectState {
    NimbleSerializeParticipantConnectStateNormal,
    NimbleSerializeParticipantConnectStateStepNotProvidedInTime,
    NimbleSerializeParticipantConnectStateStepWaitingForReconnect
} NimbleSerializeParticipantConnectState;

#endif
